apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pyspark-set
  labels:
    app: pyspark
spec:
  selector:
    matchLabels:
      app: pyspark
  serviceName: pyspark-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: pyspark
    spec:
      containers:
        - name: pyspark
          image: hello-spark:latest
          imagePullPolicy: Never
          ports:
            - name: driver-port
              containerPort: 7077
---
apiVersion: v1
kind: Service
metadata:
  name: pyspark-svc
spec:
  ports:
  - name: driver-port
    protocol: TCP 
    port: 7077
    targetPort: 7077
  clusterIP: None
  selector:
    app: pyspark
